---
title: "Transect Interactive Graphics"
date: "Generated: `r Sys.Date()`"
runtime: shiny
output:
  html_document:
    toc: true
    toc_depth: 3
    highlight: zenburn
    number_sections: false

---

```{r global_opts, include=FALSE}
knitr::opts_chunk$set(fig.path="./Figs", echo=FALSE, warning=FALSE, 
                      message=FALSE, dev='svg')
```
```{r styling}
selectInput("style", "Page Styling (not working -- needs to be changed manually):", 
            choices=c("darkly", "cyborg", "cosmo", "cerulean", 
                      "flatly", "journal", "slate", "superhero",
                      "spacelab", "readable", "sandstone"))
stylesheet <- reactive({
  paste0("../www/", input$style, "min.css")
})
```

# Info
* [code](https://github.com/ghandi9000/transects)

# Setup
__TODO__ Choose growth period to look at here.  
```{r setup, cache=FALSE}
source("setup.R")
source("helpers.R")

summTran <- reactive({
  #   samps[samps$TRAN == input$summTran, ]
  if (input$allTrans | input$byYear) tp
  else tp[tp$TRAN == input$summTran, ]  
})

summTable <- renderTable({
  dat <- summTran()
  dat <- dat[!is.na(dat[,input$summVar]), ]
  if (input$byYear) {
    dat <- dat[dat$YEAR == as.numeric(input$summYear), ]
    tab <- table(dat$TPLOT, dat$TRAN)
  } else {
    tab <- table(dat$TPLOT, dat$YEAR)
    tab <- tab[, c("87", "98", "99", "10", "11")]
  }
  if (!input$transpose) t(tab)
  else tab
  })

shinyUI(
  fluidPage(
    includeCSS("../www/slate.min.css"),
    headerPanel("Transect Summaries"),
    sidebarPanel(
      helpText("Tables display counts of summary variable."),
      #       selectInput("summYear", "Year:", choices=c(87, 98, 99, 10, 11)),
      selectInput("summTran", "Transect:", choices=sort(unique(as.character(tp$TRAN)))),
      selectInput("summVar", "Summary Variable:", choices=c("DBH","HT","HTOBS")),
      checkboxInput("byYear", "Summary by Year"),
      conditionalPanel(
        condition = "input.byYear == true",
        selectInput("summYear", "Year:", choices=c(87,98,99,10,11))
        ),
      checkboxInput("transpose", "Transpose"),
      checkboxInput("allTrans", "All Transects")
      ),
    mainPanel(
      summTable
      )
    ))

```


```{r exploratory, cache=FALSE}
observe({
  input$tabs1
  if (input$tabs1 == "Scatter 3D")
    updateCheckboxInput(session, "allPlots", label = "All Plots", value=TRUE)
})

observe({
  input$tran
  hh <- ifelse(input$tabs1 == "Position", TRUE, FALSE)
  inds <- tp$TRAN == input$tran
  if (input$tabs1 == "Position")
    inds <- inds & tp$ELEVCL == "HH"
  updateSelectInput(session, "plot", "Plot:",
                    choices=sort(unique(tp[inds, "TPLOT"])))
  })

getData <- reactive({
  if (input$allPlots == TRUE) {
    tp[tp$TRAN == as.character(input$tran), ]
  } else
    tp[tp$TRAN == as.character(input$tran) &
         tp$TPLOT == as.numeric(input$plot), ]
})

scatter <- renderPlot({
  data <- getData()
  color <- ifelse(input$color, input$colorBy, "NULL")
  shape <- ifelse(input$shape, input$shapeBy, "NULL")
  size <- ifelse(input$size, input$sizeBy, "NULL")
  x <- input$xVar
  y <- input$yVar
  if (input$scale) {
    if (input$center)
      data[,c(x, y)] <- scale(data[,c(x, y)])
    else
      data[,c(x, y)] <- scale(data[,c(x, y)], center = FALSE)
  }
  
  if (input$kmeans) {
    k <- as.numeric(input$numK)
    cl <- kmeans(na.omit(data[,c(x, y)]), centers = k)
    data[!is.na(data[,x]) & !is.na(data[,y]), "cluster"] = factor(cl$cluster)
    color = "cluster"
  }
  
  p1 <- ggplot(data, aes_string(x, y, color=color, size=size, shape=shape))
  p1 <- p1 + geom_point(alpha=0.5, na.rm=T) +
    ggtitle(paste0("Transect: ", input$tran, ", ", y, " vs ", x, "\nPlots:",
                   paste(sort(unique(data$TPLOT)), collapse=",")))
  if (input$split)
    p1 <- p1 + facet_wrap(as.formula(paste("~", input$splitBy)))
  
  if (input$smooth)
    p1 <- p1 + geom_smooth(method = input$splineType, 
                           level = as.numeric(input$conf), na.rm=T)
  print(p1)
})

scatter3d <- renderPlot({
  require(lattice)
  require(rgl)
  require(RColorBrewer)
  data <- getData()
  
  if (input$package3d == "lattice") {
    form <- paste0(input$zVar3d, "~", input$xVar3d, "*", input$yVar3d)
    if (input$split3d)
      form <- paste0(form, "|", input$split3dBy)
    cloud(as.formula(form), data=data)
    } else if (input$package3d == "rgl") {
      pal <- brewer.pal(length(unique(data$SPEC)), "Greens")
      data$col <- pal[as.numeric(data$SPEC)]
      plot3d(data[,input$xVar3d], data[,input$yVar3d], data[,input$zVar3d],
             xlab=input$xVar3d, ylab=input$yVar3d, zlab=input$zVar3d,
             type="s", alpha=0.5, col=data$col)
      title3d(main=paste0("Transect: ", input$tran, ", Plot(s): ",
                          paste(sort(unique(data$TPLOT)), collapse=",")),
              pch=2)
      axes3d()
      legend3d()
    }
})

posCl <- reactive({
  data <- getData()
  data <- data[!is.na(data$HR) & !is.na(data$DIST),]  
  k <- as.numeric(input$kPos)
  vars <- input$kmeansVars
  if (input$scalePos)
    data[,vars] <- scale(data[,vars])
  kmeans(data[complete.cases(data[,vars]),vars], centers = k)
})

position <- renderPlot({
  require(plotrix)
  color <- ifelse(input$colorPoints, input$colorPointsBy, "NULL")
  shape <- ifelse(input$shapePoints, input$shapePointsBy, "NULL")
  size <- ifelse(input$sizePoints, input$sizePointsBy, "NULL")
  data <- getData()
  data <- data[!is.na(data$HR) & !is.na(data$DIST),]
  
  if (input$kmeansPos) {
    cl <- posCl()
#     vars <- attr(cl$centers, "dimnames")[[2]]
    vars <- input$kmeansVars
    data[complete.cases(data[,vars]), "cluster"] <- factor(cl$cluster)
    color <- "cluster"
  }
  
  if (input$cartesian) {
    p1 <- ggplot(data, aes_string("X", "Y", color=color, shape=shape, 
                                  size=size))
    if (input$jitter)
      p1 <- p1 + geom_jitter(position = position_jitter(width=0.1, height=0.1),
                             alpha=0.5)
    else
      p1 <- p1 + geom_point(alpha=0.5)
    
    if (input$pointsByYear)
      p1 <- p1 + facet_wrap(~YEAR)
    
    if (input$addTRAD & !input$allPlots) {
      rs <- data %>% group_by(YEAR) %>% summarise(TRAD=unique(TRAD))
      ps <- circ(rs[["TRAD"]], rs[["YEAR"]])
      p1 <- p1 + geom_path(data=ps, aes(X, Y, color=YEAR, lty=YEAR))
    }
    if (input$addABSRAD & !input$allPlots) {
      rs <- data %>% group_by(YEAR) %>% summarise(ABSRAD=unique(ABSRAD))
      ps <- circ(rs[["ABSRAD"]], rs[["YEAR"]])
      p1 <- p1 + geom_path(data=ps, aes(X, Y, color=YEAR, lty=YEAR))
    }
    if (input$kmeansPos && input$kmeansLegend) {
      text <- apply(cl$centers, 1, function(r) paste(round(as.numeric(r),2), collapse=":"))
      name = paste(colnames(cl$centers), collapse=":")
      p1 <- p1 + scale_colour_discrete(name=name, breaks=attr(cl$centers, "dimnames")[[1]],
                                     labels=text)
      }
    print (p1)
  } else {
    polar.plot(data$DIST, polar.pos=(data$HR%%12)/max(data$HR) * 360, 
               start=90, clockwise=T, line.col="red",
               main=paste0("Transect (HH): ", input$tran, ", Plot: ", 
                           paste(sort(unique(data$TPLOT)), collapse=",")))
    }
  })

shinyUI(fluidPage(
  headerPanel("Exploratory Graphics"),
  sidebarPanel(
      selectInput("tran", "Transect:", 
                  choices=sort(unique(as.character(tp$TRAN)))),
      selectInput("plot", "Plot:", choices=sort(unique(tp$TPLOT))),
      checkboxInput("allPlots", "All Plots"),

      ## Scatter plot specific
      conditionalPanel(
        condition = "input.tabs1 == 'Scatter'",
        selectInput("xVar", "X:", choices=c("DBH", "BA", "BV", "HT", "HTOBS")),
        selectInput("yVar", "Y:", choices=c("HT", "HTOBS", "DBH", "BA", "BV")),
        checkboxInput("scale", "Scale Variables"),
        conditionalPanel(
          condition = "input.scale == true",
          checkboxInput("center", "Center", value = TRUE)
          ),
        checkboxInput("kmeans", "Kmeans"),
        conditionalPanel(
          condition = "input.kmeans == true",
          textInput("numK", "#Clusters", value=5)
          ),
        checkboxInput("color", "Color"),
        checkboxInput("size", "Size"),
        checkboxInput("shape", "Shape"),
        checkboxInput("split", "Split Graphs"),
        checkboxInput("smooth", "Add Spline"),
        
        conditionalPanel(
          condition = "input.split == true",
          selectInput("splitBy", "Split:", 
                      choices=c("YEAR", "ELEVCL", "ASPCL", "SPEC"))
          ),
        conditionalPanel(
          condition = "input.color == true",
          selectInput("colorBy", "Color:", 
                      choices=c("YEAR", "SPEC", "STAT"))
          ),
        conditionalPanel(
          condition = "input.size == true",
          selectInput("sizeBy", "Size:", 
                      choices=c("DBH", "BA", "BV", "HT"))
          ),
        conditionalPanel(
          condition = "input.shape == true",
          selectInput("shapeBy", "Shape:",
                      choices=c("SPEC", "ASPCL", "ELEVCL", "STAT"))
          ),
        conditionalPanel(
          helpText("lm = linear model\nglm = generalized linear model (normal)"),
          condition = "input.smooth == true",
          selectInput("splineType", "Spline Method:",
                      choices=c("loess", "lm", "glm")),
          sliderInput("conf", "Confidence Level:", min=0, max=1, value=0.95)
          )
        ),
      
      ## 3D scatter
      conditionalPanel(
        condition = "input.tabs1 == 'Scatter 3D'",
        helpText("NOTE: Use 'All Plots' whne using variables like 'ELEV'"),
        selectInput("package3d", "Graphics Framework",
                    choices=c("lattice", "rgl")),
        selectInput("zVar3d", "Z:",
                    choices=c("HT", "HTOBS", "BV", "BA", "DBH")),
        selectInput("yVar3d", "Y:",
                    choices=c("ELEV", "HT", "HTOBS", "BV", "BA", "DBH")),
        selectInput("xVar3d", "X:",
                    choices=c("BA", "HT", "HTOBS", "BV", "ELEV", "DBH")),
        conditionalPanel(
          condition = "input.package3d == 'lattice'",
          checkboxInput("split3d", "Split"),
          conditionalPanel(
            condition = "input.split3d == true",
            selectInput("split3dBy", "Split By:",
                        choices=c("ELEVCL", "ASPCL", "SPEC"))
            )
          )
        ),
      
      ## Position
      conditionalPanel(
        helpText("NOTE: We only have position data for high high (HH) plots."),
        condition = "input.tabs1 == 'Position'",
        checkboxInput("cartesian", "Cartesian"),
        conditionalPanel(
          condition = "input.cartesian == true",
          checkboxInput("jitter", "Jitter"),
          checkboxInput("kmeansPos", "Kmeans"),
          conditionalPanel(
            condition = "input.kmeansPos == true",
            checkboxInput("scalePos", "Scale first", TRUE),
            checkboxGroupInput("kmeansVars", "Cluster By:",
                               choices=c("BA","BV", "DBH","HT","HTOBS","X","Y"),
                               selected=c("BA", "HT")),
            textInput("kPos", "#Clusters:", value=5),
            checkboxInput("kmeansLegend", "Show K-means values")
            ),
          checkboxInput("pointsByYear", "Split Years"),
          conditionalPanel(
            condition = "input.allPlots != true",
            checkboxInput("addTRAD", "Tree Radius"),
            checkboxInput("addABSRAD", "ABBA Radius")
            ),
          checkboxInput("colorPoints", "Color"),
          conditionalPanel(
            condition = "input.colorPoints == true",
            selectInput("colorPointsBy", "Color:",
                        choices=c("SPEC", "YEAR", "STAT", "CANHT"))
            ),
          checkboxInput("shapePoints", "Shape"),
          conditionalPanel(
            condition = "input.shapePoints == true",
            selectInput("shapePointsBy", "Shape:",
                        choices=c("SPEC", "YEAR", "STAT"))
            ),
          checkboxInput("sizePoints", "Size"),
          conditionalPanel(
            condition = "input.sizePoints == true",
            selectInput("sizePointsBy", "Size:",
                        choices=c("BA", "DBH", "BV", "HT", "HTOBS", "CANHT"))
            )
          )
        )
    ),
  
  mainPanel(
    tabsetPanel(
      id = "tabs1",
      tabPanel("Position", position),
      tabPanel("Scatter", scatter),
      tabPanel("Scatter 3D", scatter3d)
        )
    
    )
  ))

```